Fix outdated and too-strict requirements
A friend of mine tried this out and got the following error:

    ERROR: Ignored the following versions that require a different python version: 6.3.0 Requires-Python <3.11,>=3.6; 6.3.1 Requires-Python <3.11,>=3.6; 6.3.2 Requires-Python <3.11,>=3.6; 6.4.0 Requires-Python <3.11,>=3.6
    ERROR: Could not find a version that satisfies the requirement PySide6==6.2.4 (from versions: 6.4.0.1, 6.4.1, 6.4.2, 6.4.3, 6.5.0, 6.5.1, 6.5.1.1, 6.5.2, 6.5.3, 6.6.0, 6.6.1, 6.6.2)
    ERROR: No matching distribution found for PySide6==6.2.4

... but reported that making the appropriate changes to the
`requirements.txt` file fixed his issues.  I've gone ahead and included
those changes here.

(Thanks Matt!)

On another note, I just realized that this means it's working on
Windows!  Hurrah!  Cross-platform-ability (at least on Linux and
Windows) is confirmed!  (I had no idea whether it'd actually work or
not.)